2-ə bölünən dəyərlərdən ibarət (1 dən 100-ə kimi) array data strukturu yarat

In [72]:
import numpy as np
a = np.arange(2, 101, 2)
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Yaradılan həmin array data strukturunu 5 sətir və 10 sütun halına sal

In [73]:
import numpy as np
a = np.arange(2, 101, 2).reshape(5,10)
print(a)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


Random rəqəmlərdən ibarət array yaradın. Daha sonra artma sırası ilə düzün

In [75]:
import numpy as np
a=np.random.randint(1,100,10)
b=np.sort(a)
print(a)
print(f"Artma sirasi ile duzulen:{b}")

[27 92 69 25 36 85 67 78 87 26]
Artma sirasi ile duzulen:[25 26 27 36 67 69 78 85 87 92]


Array data strukturunu düzləşdir yəni ilk yaradıldığı hala qaytar

In [77]:
import numpy as np

a = np.arange(2, 101, 2).reshape(5,10)  
a_flattened = a.flatten()

print(a_flattened)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Array-də 23-dən kiçik olanları saxla

In [87]:
import numpy as np

a = np.arange(2, 101, 2).reshape(5,10)

filtered_values = np.where(a < 23,a,0)

print(filtered_values)


[[ 2  4  6  8 10 12 14 16 18 20]
 [22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


0-lardan ibarət olan 4 sətir və 6 sütundan ibarət array yarat

In [25]:
zero=np.zeros((4,6))
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


1-lərdən ibarət olan 4 sətir və 6 sütundan ibarət array yarat

In [24]:
ones=np.ones((4,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Hər iki array-i vertikal şəkildə birləşdir

In [27]:
vertical= np.vstack((zeros,ones))
print(vertical)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Hər iki array-i horizontal şəkildə birləşdir

In [28]:
horizontal = np.hstack((zeros, ones))
print(horizontal)

[[0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]]


Dəyərləri 1-dən 25-ə kimi (24 daxildir) 5 sətir və 5 sütundan ibarət array yarat

In [30]:
a=np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Array-də ilk sətirin sonuncu dəyərini və son sətrin ilk dəyərini filterlə

In [91]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
b = np.array([a[0, -1], a[-1, 0]])
print(b)

[ 5 21]


Array-də bütün sətirlərin və 3-cü və 4-cü dəyərlərini filterlə

In [100]:
import numpy as np
a=np.arange(1,26).reshape(5,5)

filtered_values = a[:,3:5]

print(filtered_values)

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


Array-də maksimum dəyəri göstər

In [32]:
a=np.random.randint(1,100,10)
b=np.max(a)
print(a)
print(b)

[85 76 64 54 67 91 43 29 15  8]
91


Array-də ortalama dəyəri göstər

In [35]:
a=np.random.randint(1,100,10)
b=np.mean(a)
print(a)
print(b)

[ 8 12 92 12 67 75 92  8  7 42]
41.5


Array-də median dəyəri göstər

In [36]:
a=np.random.randint(1,100,10)
b=np.median(a)
print(a)
print(b)

[83 83 58 92 71 13 57 69 37 17]
63.5


Bu array-də minimum dəyərin indeksini göstər

In [40]:
a=np.random.randint(1,100,10)
b=np.min(a)
min_index = np.argmin(a)
print(a)
print(b)
print(min_index)

[25  7 61 41 35 29 26 35 63 74]
7
1


Bu array-də maksimum dəyərin indeksini göstər

In [43]:
a=np.random.randint(1,100,10)
b=np.max(a)
max_index = np.argmax(a)
print(a)
print(b)
print(max_index)

[16 39 66 19 49 75 47 92 61 45]
92
7


adlardan ibarət olan array yarat

In [46]:
a=np.array([["Xeyale","Esmer"],["Nijat","Edalet"]])
print(a)

[['Xeyale' 'Esmer']
 ['Nijat' 'Edalet']]


bu arraydaki adları əlifba sırası ilə düz

In [50]:
a=np.array([["Xeyale","Esmer"],["Nijat","Edalet"]])
b=np.sort(a)
print(a)
print(f"Elifba sirasi ile olan:\n{b}")

[['Xeyale' 'Esmer']
 ['Nijat' 'Edalet']]
Elifba sirasi ile olan:
[['Esmer' 'Xeyale']
 ['Edalet' 'Nijat']]


Array-də olan bütün adların ilk hərfini böyük saxla qalan hərfləri kiçilt

In [52]:
a=np.array([["xeYaLe","esMEr"],["nIJat","eDAlEt"]])
b = np.char.capitalize(a)
print(a)
print(f"Ilk hərfini böyük olan:\n{b}")

[['xeYaLe' 'esMEr']
 ['nIJat' 'eDAlEt']]
Ilk hərfini böyük olan:
[['Xeyale' 'Esmer']
 ['Nijat' 'Edalet']]


A hərfi ilə başlayan adları sil

In [56]:
a=np.array(("Aydan","Hesen","Ayla","Xeyale","Kenan","Aylin"))
filtered_names = [name for name in a if not name.startswith("A")]
print(a)
print(filtered_names)

['Aydan' 'Hesen' 'Ayla' 'Xeyale' 'Kenan' 'Aylin']
['Hesen', 'Xeyale', 'Kenan']


t hərfi ilə bitən adları sil

In [58]:
a=np.array(("Aydan","Seadet","Ayla","Nihat","Kenan","Nicat"))
filtered_names = [name for name in a if not name.endswith("t")]
print(a)
print(filtered_names)

['Aydan' 'Seadet' 'Ayla' 'Nihat' 'Kenan' 'Nicat']
['Aydan', 'Ayla', 'Kenan']



Create a list of 1000 random numbers and using filter function remove all not perfect numbers. A perfect number is a number that is equal to the sum of its divisors(excluding itself).

6 = 1 + 2 + 3

In [59]:
def perfect(number):
    bolenler=[]
    for i in range(1,number):
        if number%i==0:
            bolenler.append(i)
    if sum(bolenler)==number:
        print("perfect")
    else:
        print("not perfect")
perfect(6)

perfect


Using filter function remove all special characters (., !, &, etc.) from a string.

In [61]:
def func(a):
    olmaz=".,!,&,*,# "
    for i in a:
        if i in olmaz:
            return False
    return True
a="Hello, World! This is a test: 123 &*#"
cumle = ''.join(filter(func, a))
print(cumle)

HelloWorldThisisatest:123
