In [2]:
import numpy as np

Create a 1D numpy array

In [3]:
np.array([1,3,5])

array([1, 3, 5])

Create a 2D numpy array

In [5]:
np.array([[1,3,5],[7,9,11]])

array([[ 1,  3,  5],
       [ 7,  9, 11]])

Create a 10D numpy array

In [8]:
np.array([1,3,5], ndmin=10)

array([[[[[[[[[[1, 3, 5]]]]]]]]]])

Create an array of 10 zeros

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of (5,2) ones



In [10]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Create an array of 10 threes

In [11]:
np.array(3, ndmin=10)

array([[[[[[[[[[3]]]]]]]]]])

Create an array of integers in range from 10 to 100

In [12]:
np.arange(10,100, dtype="i")

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99], dtype=int32)

Create an array of evenly spaced numbers from 1 to 10

In [19]:
np.linspace(start=1,stop=10,num=4)

array([ 1.,  4.,  7., 10.])

Create an array of 10 random numbers

In [32]:
np.random.rand(10)

array([0.10838471, 0.79143788, 0.27103294, 0.64394533, 0.32369556,
       0.47221871, 0.22376198, 0.81102927, 0.88592348, 0.92977333])


Create a 5x2 zero matrix

In [28]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Create a 10x10 matrix of ones

In [29]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Create a 5x5 matrix of random numbers

In [55]:
np.random.rand(5,5)

array([[0.74726014, 0.09925412, 0.33051141, 0.15563487, 0.87067514],
       [0.93085917, 0.76217756, 0.48198331, 0.02480256, 0.7699138 ],
       [0.9341088 , 0.92701784, 0.32011818, 0.05153829, 0.32719638],
       [0.31698636, 0.15346679, 0.56209098, 0.9388364 , 0.46076079],
       [0.19941272, 0.32744743, 0.72483987, 0.99855153, 0.40140774]])

Create an array of 5 numbers and display each of its elements

In [34]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

Create a 3x3 matrix of random numbers and display all numbers


[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

OUTPUT: 1 2 3 4 5 6 7 8 9

In [62]:
arr= np.random.randint(1, 100, size=(3, 3))
for i in arr:
    print(" ".join(map(str, i)))

41 39 78
66 53 3
66 63 84


Create a 3x4 array filled with values from 24 to 32

In [70]:
arr= np.arange(24, 36).reshape(3,4)
arr

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

Create a 3x4 array of evenly distributed numbers between 0 and 1. Display its shape and the number of dimensions.

In [73]:
arr= np.linspace(0,1).reshape(3,4)
arr

ValueError: cannot reshape array of size 50 into shape (3,4)

Create a 5x5 identity matrix

In [75]:
arr= np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


Create a 6x6 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5, 6.

Reshape a 9x4 matrix into a 2x18 matrix

In [79]:
arr= np.random.rand(9, 4)
yeni= arr.reshape(2,18)
yeni

array([[0.5915911 , 0.35446109, 0.21429164, 0.13882892, 0.66931038,
        0.1635599 , 0.01707412, 0.30395352, 0.18384931, 0.02426117,
        0.95072233, 0.43984143, 0.31288627, 0.75530044, 0.22527959,
        0.89231202, 0.11336556, 0.88304372],
       [0.42070607, 0.80751273, 0.06767366, 0.38448432, 0.2356086 ,
        0.81230454, 0.88241002, 0.49131139, 0.5123907 , 0.98070378,
        0.55032454, 0.83800745, 0.10797875, 0.95370058, 0.54389716,
        0.53911734, 0.01529641, 0.8775936 ]])

Create a 3x4 matrix of random numbers and transpose it.

In [83]:
arr= np.random.rand(3,4)
yeni= arr.transpose()
yeni

array([[0.63972707, 0.49400476, 0.43822114],
       [0.19050106, 0.46890982, 0.3544362 ],
       [0.81006019, 0.37744345, 0.77644606],
       [0.69385462, 0.5279986 , 0.85837236]])

Create a 5x5 matrix of evenly 25 evenly distributed numebrs between 0 and 25. Find the sum of all elements, sum of all rows, sum of all columns.(hem for-la yazin hem for-suz yazin)

In [113]:
arr= np.linspace(0,25,25)
yeni= arr.reshape(5,5)
topla= np.sum(yeni)
print(f"cem; {topla}")
setir=np.sum(yeni, axis=1)
print(f"setirlerin cemi; {setir} ")
sutun=np.sum(yeni, axis=0)
print(f"sutunlarin cemi; {sutun} ")


cem; 312.5
setirlerin cemi; [ 10.41666667  36.45833333  62.5         88.54166667 114.58333333] 
sutunlarin cemi; [52.08333333 57.29166667 62.5        67.70833333 72.91666667] 


Create a vector and find its magnitude

In [89]:
arr= np.array([1,3,5])
np.linalg.norm(arr)

5.916079783099616

Create a vector of 100 random integers and display unqiue values

In [97]:
arr = np.random.randint(0, 100, 100)
un=np.unique(arr)
print(arr)
print(un)

[50 64 51 68 72 66 43 14 99 11  2 53 83 53 25 70 61  7 58 12  4 12 48 58
 75 92 63 55 79 24 47 10 53 78 72  7 35 80 67 18 35 63 70 47 73 31 98 64
  5 36 30 32 57 86 33 88 72 11 71 69 16 15 10 30 84 83 91 78 43 24 92 82
 56 97  7 41 32 68  3 55 65 38  7 37 11 31 38  3 77 49 66 11 65 42 37 89
 77 26 49  3]
[ 2  3  4  5  7 10 11 12 14 15 16 18 24 25 26 30 31 32 33 35 36 37 38 41
 42 43 47 48 49 50 51 53 55 56 57 58 61 63 64 65 66 67 68 69 70 71 72 73
 75 77 78 79 80 82 83 84 86 88 89 91 92 97 98 99]


Create a 5x5 vector of random integers and find the product of all elements, product of all columns, product of all rows.

In [110]:
arr = np.random.rand(5,5)
topla= np.sum(arr)
print(f"cem; {topla}")
setir=np.sum(arr, axis=1)
print(f"setirlerin cemi; {setir} ")
sutun=np.sum(arr, axis=0)
print(f"sutunlarin cemi; {sutun} ")

cem; 11.582612112439966
setirlerin cemi; [1.98911156 2.1625793  1.40368083 3.07059139 2.95664904] 
sutunlarin cemi; [3.0238255  2.01034311 2.14730239 2.62980615 1.77133496] 


Create a random array and display it as an image