In [29]:
import numpy as np

In [2]:
a= np.array([1,2,5,6,7,0,44,9])
b= np.array([11,6,8,9,87,69])

In [3]:
bos = []
for i in a:
    if i not in b:
        bos.append(i)

print(bos)

[1, 2, 5, 7, 0, 44]


In [7]:
m = a[0]
m_i = 0
for i in range(len(a)):
    if a[i] > m:
        m=a[i]
        m_i=i
print(m_i)

6


In [8]:
a.argmin()

5

-----

In [40]:
a = np.arange(25)
a = a.reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
z = np.random.shuffle(a)

In [45]:
z

In [17]:
a[[0,1,2,3,4], [0,1,2,3,4]]

array([ 0,  6, 12, 18, 24])

In [20]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [22]:
nans = np.array([2, 4, np.nan, 6, 8, np.nan, 10, 12, np.nan, np.nan, 65])
nans

array([ 2.,  4., nan,  6.,  8., nan, 10., 12., nan, nan, 65.])

In [23]:
np.isnan(nans)

array([False, False,  True, False, False,  True, False, False,  True,
        True, False])

In [24]:
adlar = np.array(['nicat', 'esmer', 'xeyale', 'fuad', 'edalet'])
adlar

array(['nicat', 'esmer', 'xeyale', 'fuad', 'edalet'], dtype='<U6')

In [28]:
np.char.find(adlar, 'a')

array([ 3, -1,  3,  2,  2])

In [53]:
a = np.random.randint(1, 51, (5,5))
a

array([[ 7,  2,  5,  6, 35],
       [29, 12,  8,  7,  4],
       [24, 45, 33, 13,  8],
       [44, 45, 27, 34, 49],
       [13, 47, 25, 39, 16]])

In [54]:
np.sort(a)

array([[ 2,  5,  6,  7, 35],
       [ 4,  7,  8, 12, 29],
       [ 8, 13, 24, 33, 45],
       [27, 34, 44, 45, 49],
       [13, 16, 25, 39, 47]])

In [56]:
np.sort(a, axis = 0)

array([[ 7,  2,  5,  6,  4],
       [13, 12,  8,  7,  8],
       [24, 45, 25, 13, 16],
       [29, 45, 27, 34, 35],
       [44, 47, 33, 39, 49]])