In [1]:
import numpy as np

Create a 1D numpy array

In [3]:
a = np.array([2, 4, 6, 8])
a

array([2, 4, 6, 8])

Create a 2D numpy array

In [5]:
b = np.array([[2,4,6], [1,3,5]])
b

array([[2, 4, 6],
       [1, 3, 5]])

Create a 10D numpy array

In [9]:
c = np.array([
    [[[[[[[[[
        [1, 2],
        [3, 4]
    ]]]]]]]]]
])
c

array([[[[[[[[[[[1, 2],
                [3, 4]]]]]]]]]]])

Create an array of 10 zeros

In [11]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of (5,2) ones



In [15]:
one = np.ones((2, 5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Create an array of 10 threes

In [16]:
three = np.ones(10) * 3
three

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

Create an array of integers in range from 10 to 100

In [17]:
range_10_100 = np.arange(10, 100)
range_10_100

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

Create an array of evenly spaced numbers from 1 to 10

In [23]:
evenly = np.linspace(1, 10)
evenly

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

Create an array of 10 random numbers

In [30]:
rand = np.random.rand(10)
rand

array([0.77262418, 0.20414689, 0.72933259, 0.37840578, 0.82732682,
       0.92314412, 0.96080726, 0.62652352, 0.57592772, 0.1401939 ])


Create a 5x2 zero matrix

In [32]:
zero = np.zeros((5,2))
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Create a 10x10 matrix of ones

In [38]:
one = np.ones((10,10))
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Create a 5x5 matrix of random numbers

In [43]:
rand = np.random.random((5, 5))
rand

array([[0.40384325, 0.21567354, 0.61868333, 0.09143543, 0.7886585 ],
       [0.16072155, 0.58551585, 0.72900193, 0.80368983, 0.02674365],
       [0.82844869, 0.26942217, 0.08998177, 0.69680772, 0.79449762],
       [0.26083137, 0.05146471, 0.23426291, 0.47045541, 0.07872793],
       [0.67732263, 0.26786634, 0.16378625, 0.33880404, 0.56371625]])

Create an array of 5 numbers and display each of its elements

In [58]:
arr = np.random.rand(5)
print(arr)

for i in arr:
    print(i)

[0.73605647 0.32066467 0.74784794 0.03764502 0.29871701]
0.7360564678470145
0.320664670825473
0.7478479411108833
0.0376450151319081
0.29871701085218616


Create a 3x3 matrix of random numbers and display all numbers


[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

OUTPUT: 1 2 3 4 5 6 7 8 9

In [68]:
rands = np.random.randint(1, 10, (3,3))
rands

for i in rands.flatten():
    print(i)

9
8
7
9
9
8
8
3
7


Create a 3x4 array filled with values from 24 to 32

In [74]:
a = np.arange(24, 36).reshape(3,4)
a

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

Create a 3x4 array of evenly distributed numbers between 0 and 1. Display its shape and the number of dimensions.

In [83]:
even = np.linspace(0, 1, 12).reshape(3,4)
even

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

Create a 5x5 identity matrix

In [97]:
iden = np.eye(6,6)
iden

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])


Create a 6x6 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5, 6.

In [94]:
# for x in iden:
#     for z in x:
#         print(z)

In [95]:
vuruq = 1
for i in range(6):
    iden[i, i] *= vuruq
    vuruq+=1
print(iden)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [98]:
for i in range(6):
    iden[i, i] *= (i+1)
print(iden)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Reshape a 9x4 matrix into a 2x18 matrix

Create a 3x4 matrix of random numbers and transpose it.

Create a 5x5 matrix of evenly 25 evenly distributed numebrs between 0 and 25. Find the sum of all elements, sum of all rows, sum of all columns.(hem for-la yazin hem for-suz yazin)

Create a vector and find its magnitude

Create a vector of 100 random integers and display unqiue values

Create a 5x5 vector of random integers and find the product of all elements, product of all columns, product of all rows.

Create a random array and display it as an image