In [1]:
# Lazım olan kitabxanalar
import numpy as np

In [46]:
# array() metodu ilə int64 data növlü array data strukturunun yaradılması
int_array_64 = np.array(object = [1, 2, 3, 4])
int_array_64

array([1, 2, 3, 4])

In [47]:
int_array_64 = np.array(object = [1, 2, 3, 4], dtype = 'int64')
int_array_64

array([1, 2, 3, 4], dtype=int64)

In [48]:
float_array_128 = np.array(object = [1, 2, 3, 4], dtype = 'float')
float_array_128

array([1., 2., 3., 4.])

In [2]:
# arange() metodu ilə array data strukturunun yaradılması
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
for a in range(2,10,2):
    print(float(a))

2.0
4.0
6.0
8.0


In [8]:
# arange() metodu ilə bir ölçülü array data strukturunun yaradılması
np.arange(start = 1, stop = 10, step = 2)

array([1, 3, 5, 7, 9])

In [9]:
# arange() metodu ilə bir ölçülü array data strukturunun yaradılması
np.arange(start = 1, stop = 10, step = 2, dtype = np.float32)

array([1., 3., 5., 7., 9.], dtype=float32)

In [10]:
# linspace() metodu ilə seçilən intervala əsasən bərabər məsafəli dəyərlərdən ibarət array data strukturunun yaradılması
np.linspace(start = 1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [7]:
# linspace() metodu ilə seçilən intervala əsasən bərabər məsafəli dəyərlərdən ibarət array data strukturunun yaradılması
np.linspace(start = 1, stop = 10, num = 4, endpoint = False)

array([1.  , 3.25, 5.5 , 7.75])

In [12]:
# linspace() metodu ilə seçilən intervala əsasən bərabər məsafəli dəyərlərdən ibarət array data strukturunun yaradılması
np.linspace(start = 1, stop = 10, num = 4, endpoint = False, retstep = True)

(array([1.  , 3.25, 5.5 , 7.75]), 2.25)

In [17]:
# zeros() metodu ilə array data strukturunun yaradılması
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
# zeros() metodu ilə array data strukturunun yaradılması
np.zeros(shape = (2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# ones() metodu ilə array data strukturunun yaradılması
ones = np.ones(shape = 3)

In [28]:
# ones() metodu ilə array data strukturunun yaradılması
ones = np.ones(shape = (2, 3), dtype = np.int32)

In [20]:
# repeat() metodu ilə array data strukturunun yaradılması
np.repeat(a = 3, repeats = 3)

array([3, 3, 3])

In [18]:
# arange() metodu ilə array data strukturunun yaradılması
array = np.arange(start = 1, stop = 5)
array

array([1, 2, 3, 4])

In [19]:
# repeat() metodu ilə array data strukturunun yaradılması
np.repeat(a = array, repeats = 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [21]:
# array() metodu ilə array data strukturunun yaradılması
array = np.array(object = [1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [25]:
# dtype atributu ilə array data strukturunun data növünün göstərilməsi
array.dtype

dtype('int32')

In [22]:
# ndim atributu ilə array data strukturunun ölçüsünün göstərilməsi
array.ndim

1

In [26]:
array.size

4

In [29]:
# shape atributu ilə array data strukturunda olan sütun və sətir sayının göstərilməsi
ones.shape

(2, 3)

In [30]:
# arange() metodundan istifadə edərək array data strukturunun yaradılması
array = np.arange(start = 1, stop = 8, dtype = np.int32)
array

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# median() metodu ilə array data strukturunda median dəyərin tapılması
np.median(a = array)

4.0

In [35]:
# mean() metodu ilə array data strukturunda ortalama dəyərin tapılması
array.mean()

4.0

In [33]:
# max() metodu ilə array data strukturunda maksimum dəyərin tapılması
array.max()

7

In [30]:
# min() metodu ilə array data strukturunda minimum dəyərin tapılması
array.min()

1

In [31]:
# sum() metodu ilə array data strukturunda dəyərlərin cəminin tapılması
array.sum()

28

In [32]:
# var() metodu ilə array data strukturunda variasiya dəyərinin tapılması
array.var()

4.0

In [33]:
# std() metodu ilə array data standard yayılma dəyərinin tapılması
array.std()

2.0

In [34]:
# add() metodu ilə array data strukturunun dəyərlərinin üzərinə verilən dəyərin gəlinməsi
np.add(array, 2)

array([3, 4, 5, 6, 7, 8, 9])

In [35]:
# Bu metodun 2 eyni və ya fərqli array data strukturuna tətbiq olunması
np.add(array, array)

array([ 2,  4,  6,  8, 10, 12, 14])

In [36]:
# subtract() metodu ilə array data strukturunun dəyərlərindən verilən dəyərin çıxılması
np.subtract(array, 2)

array([-1,  0,  1,  2,  3,  4,  5])

In [37]:
# multiply() metodu ilə array data strukturunun dəyərlərindən verilən dəyərə vurulması
np.multiply(array, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [38]:
# Bu metodun 2 eyni və ya fərqli array data strukturuna tətbiq olunması
np.multiply(array, array)

array([ 1,  4,  9, 16, 25, 36, 49])

In [39]:
# divide() metodu ilə array data strukturunun dəyərlərindən verilən dəyərə bölünməsi
np.divide(array, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [40]:
# Bu metodun 2 eyni və ya fərqli array data strukturuna tətbiq olunması
np.divide(array, array)

array([1., 1., 1., 1., 1., 1., 1.])

In [41]:
# power() metodu ilə array data strukturunun dəyərlərinin verilən dəyərə görə qüvvətə yüksəldilməsi
np.power(array, 2)

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [42]:
# Bu metodun 2 eyni və ya fərqli array data strukturuna tətbiq olunması
np.power(array, array)

array([     1,      4,     27,    256,   3125,  46656, 823543])

In [43]:
# arange() metodundan istifadə edərək array data strukturunun yaradılması
negative_positive_array = np.arange(start = -3, stop = 4)
negative_positive_array

array([-3, -2, -1,  0,  1,  2,  3])

In [44]:
# abs() metodu ilə array data strukturunda modul dəyərlərin tapılması
np.abs(negative_positive_array)

array([3, 2, 1, 0, 1, 2, 3])